from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts import release


def test_release_version_sources_are_consistent() -> None:
    version = release.current_version()
    release.verify_version_consistency(version)


def test_release_forbidden_paths_cover_user_and_developer_data() -> None:
    assert release.forbidden(Path("data/akdesk-fixed.db"))
    assert release.forbidden(Path(".venv/bin/python"))
    assert release.forbidden(Path("frontend/node_modules/react/index.js"))
    assert release.forbidden(Path("docs/.DS_Store"))
    assert release.forbidden(Path("cache.db-wal"))
    assert release.forbidden(Path("backend/app/main.py")) is None


def test_release_secret_scan_rejects_key_and_accepts_placeholders(tmp_path) -> None:
    safe = tmp_path / "safe"
    safe.mkdir()
    (safe / "README.md").write_text(
        "请使用自己的 FRED Key；示例为 YOUR_API_KEY。", encoding="utf-8"
    )
    release.scan_secrets(safe)
    (safe / "leak.txt").write_text("api_key = sk-" + "A1" * 20, encoding="utf-8")
    with pytest.raises(RuntimeError, match="疑似包含凭据"):
        release.scan_secrets(safe)


def test_generated_sbom_is_machine_readable() -> None:
    path = release.ROOT / "SBOM.cdx.json"
    if not path.exists():
        pytest.skip("SBOM is generated by the release gate")
    payload = json.loads(path.read_text(encoding="utf-8"))
    assert payload["bomFormat"] == "CycloneDX"
    assert payload["specVersion"] == "1.5"
    assert payload["components"]
